import { useState } from "react";
import { FiAlertCircle, FiArrowDownLeft, FiArrowUpRight, FiCalendar, FiChevronDown, FiCreditCard, FiEye, FiEyeOff, FiFlag, FiPlus, FiRefreshCw, FiSearch, FiShield, FiTarget, FiTrendingDown, FiTrendingUp } from "react-icons/fi";
import { Link } from "react-router";
import Modal from "../../../components/common/Modal.jsx";
import PageInfoButton from "../../../components/common/PageInfoButton.jsx";
import ProgressBar from "../../../components/common/ProgressBar.jsx";
import { AccountVisual } from "../../accounts/components/AccountFinancialCard.jsx";
import { formatTransactionDate, transactionCategoryIcon, TRANSACTION_LABELS, transactionTone } from "../../../shared/presentation/transaction.js";
import { dashboardAlertGuidance, formatPeriod } from "../dashboardPresentation.js";
import FinancialAlertList from "./FinancialAlertList.jsx";
import SensitiveMoney from "./SensitiveMoney.jsx";
import { dashboardClass } from "../dashboardStyles.js";

const CHART_COLORS = ["var(--dashboard-chart-1)", "var(--dashboard-chart-2)", "var(--dashboard-chart-3)", "var(--dashboard-chart-4)", "var(--dashboard-chart-5)"];
const percentage = (value, maximum) => maximum > 0 ? Math.max(0, Math.round((Number(value || 0) / Number(maximum)) * 100)) : 0;

const accountTransactionDelta = (transaction, accountId) => {
  if (transaction.status && transaction.status !== "active") return 0;
  const amount = Number(transaction.amount || 0);
  if (transaction.transaction_type === "transfer") {
    if (transaction.destination_account_id === accountId) return amount;
    if (transaction.source_account_id === accountId) return -amount;
    return 0;
  }
  if (["income", "refund"].includes(transaction.transaction_type)) return transaction.destination_account_id === accountId ? amount : 0;
  if (transaction.transaction_type === "expense") return transaction.source_account_id === accountId ? -amount : 0;
  if (transaction.transaction_type === "adjustment") return transaction.source_account_id === accountId ? amount : 0;
  if (transaction.destination_account_id === accountId) return amount;
  return transaction.source_account_id === accountId ? -amount : 0;
};

const matchesAccount = (transaction, accountId) => transaction.source_account_id === accountId || transaction.destination_account_id === accountId;
const compactDate = (value) => { if (!value) return "Tanggal belum tersedia"; const parsed = new Date(`${String(value).slice(0, 10)}T00:00:00+07:00`); return Number.isNaN(parsed.getTime()) ? String(value) : new Intl.DateTimeFormat("id-ID", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Jakarta" }).format(parsed); };
const dueLabel = (value) => { if (!value) return "Jadwal belum tersedia"; const due = new Date(`${String(value).slice(0, 10)}T00:00:00+07:00`); if (Number.isNaN(due.getTime())) return "Jadwal belum tersedia"; const today = new Date(new Date().toLocaleString("en-US", { timeZone: "Asia/Jakarta" })); today.setHours(0, 0, 0, 0); const days = Math.ceil((due.getTime() - today.getTime()) / 86_400_000); if (days < 0) return `${Math.abs(days)} hari terlambat`; if (days === 0) return "Hari ini"; return days === 1 ? "Besok" : `${days} hari lagi`; };

const filterAccountTransactions = ({ transactions, categoryFilter, typeFilter, searchTerm, categoryLookup }) => {
  const query = searchTerm.trim().toLocaleLowerCase("id-ID");
  return transactions.filter((item) => {
    if (categoryFilter !== "all" && item.category_id !== categoryFilter) return false;
    if (typeFilter !== "all" && item.transaction_type !== typeFilter) return false;
    if (!query) return true;
    return [item.description, item.merchant, categoryLookup[item.category_id]?.name, TRANSACTION_LABELS[item.transaction_type]].filter(Boolean).join(" ").toLocaleLowerCase("id-ID").includes(query);
  });
};

const transactionRowsFor = (transactions, selectedAccount) => {
  let runningBalance = Number(selectedAccount?.balance || 0); const lookup = new Map();
  for (const item of transactions) { lookup.set(item.transaction_id, runningBalance); runningBalance -= accountTransactionDelta(item, selectedAccount?.account_id); }
  return (items) => items.map((item) => ({ item, delta: accountTransactionDelta(item, selectedAccount?.account_id), balanceAfter: lookup.get(item.transaction_id) ?? Number(selectedAccount?.balance || 0) }));
};

const categoryStatistics = (expenseByCategory) => {
  const categoryTotal = expenseByCategory.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const categories = expenseByCategory.length > 5 ? [...expenseByCategory.slice(0, 4), { category_id: "other-categories", name: "Lainnya", amount: expenseByCategory.slice(4).reduce((sum, item) => sum + Number(item.amount || 0), 0) }] : expenseByCategory.slice(0, 5);
  let cursor = 0; const segments = categories.map((item, index) => { const share = categoryTotal > 0 ? (Number(item.amount || 0) / categoryTotal) * 100 : 0; const start = cursor; cursor += share; return `${CHART_COLORS[index]} ${start.toFixed(2)}% ${cursor.toFixed(2)}%`; });
  return { categoryTotal, categories, donutStyle: { background: segments.length ? `conic-gradient(${segments.join(",")})` : "var(--surface-soft)" } };
};

const planningSummary = (overview, expenseByCategory) => {
  const budgets = (overview.budgets || []).filter((item) => item.status !== "archived"); const totalBudget = budgets.reduce((sum, item) => sum + Number(item.amount || 0), 0); const usedBudget = budgets.reduce((sum, item) => sum + Number(item.used_amount || 0), 0);
  const biggestExpense = expenseByCategory.reduce((largest, item) => Number(item.amount || 0) > Number(largest?.amount || 0) ? item : largest, null);
  const recurringItems = (overview.recurring || []).filter((item) => !["paid", "cancelled", "archived"].includes(item.occurrence_status || item.status)).sort((a, b) => String(a.due_date || "9999").localeCompare(String(b.due_date || "9999"))).slice(0, 3);
  return { budgets, totalBudget, remainingBudget: Math.max(0, totalBudget - usedBudget), biggestExpense, recurringItems, goals: (overview.goals || []).filter((item) => item.status === "active").slice(0, 3), alerts: overview.alerts || [] };
};

const buildDesktopModel = ({ overview, viewModel, selectedAccountId, categoryFilter, typeFilter, searchTerm, selectedTransactionId }) => {
  const { accountBalances, categoryLookup, recentTransactions, expenseByCategory } = viewModel; const selectedAccount = accountBalances.find((item) => item.account_id === selectedAccountId) || accountBalances[0] || null;
  const selectedAccountTransactions = selectedAccount ? recentTransactions.filter((item) => matchesAccount(item, selectedAccount.account_id)) : []; const accountTransactions = filterAccountTransactions({ transactions: selectedAccountTransactions, categoryFilter, typeFilter, searchTerm, categoryLookup });
  const transactionRows = transactionRowsFor(selectedAccountTransactions, selectedAccount)(accountTransactions); const selectedTransaction = accountTransactions.find((item) => item.transaction_id === selectedTransactionId) || accountTransactions[0] || null;
  return { accountBalances, categoryLookup, expenseByCategory, selectedAccount, selectedAccountTransactions, transactionRows, selectedTransaction, ...categoryStatistics(expenseByCategory), ...planningSummary(overview, expenseByCategory) };
};

const DashboardHeader = ({ overview, displayName, balanceVisible, onToggleBalance, onRefresh, onOpenTransaction }) => <header className={dashboardClass("shared-dashboard__header")}><div><div className={dashboardClass("shared-dashboard__title-row")}><h1>Dashboard</h1><PageInfoButton title="Tentang Beranda">Beranda merangkum saldo, transaksi terbaru, alokasi, dan perhatian penting. Informasi di sini mengikuti data terbaru yang sudah diterima aplikasi.</PageInfoButton></div><p>Hai, <strong>{displayName}</strong></p></div><div className={dashboardClass("shared-dashboard__actions")}><span className={dashboardClass("shared-period-pill")}><FiCalendar aria-hidden="true" />{formatPeriod(overview.periodKey)}</span><button type="button" className={dashboardClass("shared-icon-action")} onClick={onToggleBalance} aria-label={balanceVisible ? "Sembunyikan seluruh nominal" : "Tampilkan seluruh nominal"} aria-pressed={!balanceVisible}>{balanceVisible ? <FiEye aria-hidden="true" /> : <FiEyeOff aria-hidden="true" />}</button><button type="button" className={dashboardClass("shared-icon-action")} onClick={onRefresh} aria-label="Sinkronkan data"><FiRefreshCw aria-hidden="true" /></button><button type="button" className={dashboardClass("button button--primary")} onClick={onOpenTransaction}><FiPlus aria-hidden="true" /><span>Tambah transaksi</span></button></div></header>;

const AccountSelector = ({ accountBalances, selectedAccount, onSelectAccount, balanceVisible }) => <section className={dashboardClass("shared-panel shared-account-panel")} aria-labelledby="dashboard-accounts-title"><div className={dashboardClass("shared-section-heading")}><h2 id="dashboard-accounts-title">Rekening</h2><Link to="/rekening">Kelola</Link></div>{accountBalances.length ? <><div className={dashboardClass("shared-account-carousel")} aria-label="Pilih rekening dashboard">{accountBalances.map((account) => { const selected = account.account_id === selectedAccount?.account_id; const cleanAccount = { ...account, name: account.account_name || account.name }; return <button key={account.account_id} type="button" className={dashboardClass(`shared-account-card${selected ? " is-selected" : ""}`)} onClick={() => onSelectAccount(account.account_id)} aria-pressed={selected} aria-label={`Pilih ${cleanAccount.name}`} data-dashboard-account={account.account_id}><AccountVisual account={cleanAccount} carousel /><span className={dashboardClass("shared-account-card__summary")}><span><small>Saldo</small><SensitiveMoney visible={balanceVisible} value={account.balance} /></span><span><small>Tersedia</small><SensitiveMoney visible={balanceVisible} value={account.available_balance ?? account.balance ?? 0} /></span></span></button>; })}</div><div className={dashboardClass("shared-account-pagination")} aria-label="Posisi rekening terpilih">{accountBalances.map((account) => <button key={account.account_id} type="button" className={dashboardClass(account.account_id === selectedAccount?.account_id ? "is-active" : "")} onClick={() => onSelectAccount(account.account_id)} aria-label={`Pilih ${account.account_name || account.name}`} />)}</div></> : <div className={dashboardClass("shared-empty-state")}><FiCreditCard aria-hidden="true" /><strong>Belum ada rekening aktif</strong><Link to="/rekening">Tambah rekening</Link></div>}</section>;

const TransactionTools = ({ bootstrap, categoryFilter, setCategoryFilter, typeFilter, setTypeFilter, searchTerm, setSearchTerm }) => <div className={dashboardClass("shared-transaction-tools")}><label><span className={dashboardClass("sr-only")}>Cari transaksi rekening terpilih</span><FiSearch aria-hidden="true" /><input type="search" value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} placeholder="Cari transaksi" /></label><label><span className={dashboardClass("sr-only")}>Filter kategori</span><select aria-label="Filter kategori" value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option value="all">Semua kategori</option>{(bootstrap?.categories || []).filter((item) => item.status === "active").map((item) => <option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select><FiChevronDown aria-hidden="true" /></label><label><span className={dashboardClass("sr-only")}>Filter jenis transaksi</span><select aria-label="Filter jenis transaksi" value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="all">Semua jenis</option>{Object.entries(TRANSACTION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><FiChevronDown aria-hidden="true" /></label><Link to="/transaksi">Lihat semua</Link></div>;

const TransactionRow = ({ row, categoryLookup, selectedTransaction, setSelectedTransactionId, balanceVisible }) => { const { item, delta, balanceAfter } = row; const category = categoryLookup[item.category_id]; const Icon = transactionCategoryIcon(category, item.transaction_type); const title = item.description || item.merchant || category?.name || "Transaksi"; const active = selectedTransaction?.transaction_id === item.transaction_id; return <tr className={dashboardClass(active ? "is-selected" : "")}><td><strong>{formatTransactionDate(item.transaction_date)}</strong><small>{item.status || "active"}</small></td><td><button type="button" className={dashboardClass("shared-transaction-select")} onClick={() => setSelectedTransactionId(item.transaction_id)} aria-pressed={active}><span className={dashboardClass(`shared-transaction-icon shared-transaction-icon--${item.transaction_type || "default"}`)}><Icon aria-hidden="true" /></span><span><strong>{title}</strong><small>{item.merchant || TRANSACTION_LABELS[item.transaction_type] || "Transaksi"}</small></span></button></td><td><span className={dashboardClass(`shared-category-chip shared-category-chip--${transactionTone(item.transaction_type)}`)}>{category?.name || TRANSACTION_LABELS[item.transaction_type] || "Lainnya"}</span></td><td>{delta < 0 ? <SensitiveMoney visible={balanceVisible} value={Math.abs(delta)} tone="negative" /> : <span>—</span>}</td><td>{delta > 0 ? <SensitiveMoney visible={balanceVisible} value={delta} tone="positive" /> : <span>—</span>}</td><td><SensitiveMoney visible={balanceVisible} value={balanceAfter} /></td></tr>; };

const AccountTransactions = ({ model, bootstrap, categoryFilter, setCategoryFilter, typeFilter, setTypeFilter, searchTerm, setSearchTerm, setSelectedTransactionId, balanceVisible }) => <section className={dashboardClass("shared-panel shared-transactions")} aria-labelledby="selected-account-transactions-title"><div className={dashboardClass("shared-transactions__header")}><div><h2 id="selected-account-transactions-title">Transaksi rekening</h2><span>{model.selectedAccount ? (model.selectedAccount.account_name || model.selectedAccount.name) : "Belum ada rekening"}</span></div><TransactionTools bootstrap={bootstrap} categoryFilter={categoryFilter} setCategoryFilter={setCategoryFilter} typeFilter={typeFilter} setTypeFilter={setTypeFilter} searchTerm={searchTerm} setSearchTerm={setSearchTerm} /></div>{model.transactionRows.length ? <div className={dashboardClass("shared-transaction-table-wrap")}><table className={dashboardClass("shared-transaction-table")}><thead><tr><th>Tanggal</th><th>Deskripsi</th><th>Kategori</th><th>Debit</th><th>Kredit</th><th>Saldo</th></tr></thead><tbody>{model.transactionRows.slice(0, 8).map((row) => <TransactionRow key={row.item.transaction_id} row={row} categoryLookup={model.categoryLookup} selectedTransaction={model.selectedTransaction} setSelectedTransactionId={setSelectedTransactionId} balanceVisible={balanceVisible} />)}</tbody></table></div> : <div className={dashboardClass("shared-empty-state")}><FiSearch aria-hidden="true" /><strong>Tidak ada transaksi yang cocok</strong><span>Ubah rekening atau filter untuk melihat aktivitas lain.</span></div>}{model.selectedTransaction ? <div className={dashboardClass("shared-selected-transaction")}><span>Transaksi dipilih</span><strong>{model.selectedTransaction.description || model.selectedTransaction.merchant || "Transaksi"}</strong><small>{model.categoryLookup[model.selectedTransaction.category_id]?.name || TRANSACTION_LABELS[model.selectedTransaction.transaction_type]} · {formatTransactionDate(model.selectedTransaction.transaction_date)}</small></div> : null}</section>;

const StatisticsPanel = ({ overview, model, balanceVisible }) => <aside className={dashboardClass("shared-dashboard__side")} aria-label="Statistik dan ringkasan dashboard"><section className={dashboardClass("shared-panel shared-statistics")} aria-labelledby="dashboard-statistics-title"><div className={dashboardClass("shared-section-heading")}><h2 id="dashboard-statistics-title">Pengeluaran</h2><Link to="/laporan">Laporan</Link></div><div className={dashboardClass("shared-statistics__summary")}><span>Total pengeluaran bulan ini</span><SensitiveMoney visible={balanceVisible} value={overview.cashFlow.expense} tone="negative" /><small>{model.expenseByCategory.length} kategori tercatat</small></div><div className={dashboardClass("shared-statistics__content")}><div className={dashboardClass("shared-donut")} style={model.donutStyle} role="img" aria-label={`Distribusi pengeluaran ${formatPeriod(overview.periodKey)}`}><span><small>{formatPeriod(overview.periodKey)}</small><strong>{model.categoryTotal ? "100%" : "0%"}</strong></span></div><ul className={dashboardClass("shared-stat-legend")}>{model.categories.length ? model.categories.map((item, index) => <li key={`${item.name}-${index}`}><i data-index={index} /><span><strong>{item.name}</strong><small><SensitiveMoney visible={balanceVisible} value={item.amount} /> · {percentage(item.amount, model.categoryTotal)}%</small></span></li>) : <li><span>Belum ada pengeluaran kategori.</span></li>}</ul></div></section><div className={dashboardClass("shared-kpi-grid")} aria-label="Ringkasan arus kas dan anggaran"><article><span><FiTrendingDown aria-hidden="true" />Arus kas bersih</span><SensitiveMoney visible={balanceVisible} value={Number(overview.cashFlow.income || 0) - Number(overview.cashFlow.expense || 0)} tone={Number(overview.cashFlow.income || 0) - Number(overview.cashFlow.expense || 0) < 0 ? "negative" : "positive"} /></article><article><span><FiTrendingUp aria-hidden="true" />Pemasukan</span><SensitiveMoney visible={balanceVisible} value={overview.cashFlow.income} tone="positive" /><ProgressBar value={overview.cashFlow.income} max={Math.max(overview.cashFlow.income, overview.cashFlow.expense, 1)} label="Proporsi pemasukan" /></article><article><span><FiShield aria-hidden="true" />Sisa anggaran</span><SensitiveMoney visible={balanceVisible} value={model.remainingBudget} /><ProgressBar value={model.remainingBudget} max={Math.max(model.totalBudget, 1)} label="Sisa anggaran" /></article></div><section className={dashboardClass("shared-largest-expense")}><span>Pengeluaran terbesar</span><strong>{model.biggestExpense?.name || "Belum tersedia"}</strong><SensitiveMoney visible={balanceVisible} value={model.biggestExpense?.amount || 0} tone="negative" /></section></aside>;

const BudgetWidget = ({ budgets, balanceVisible }) => <article className={dashboardClass("shared-panel shared-widget")}><div className={dashboardClass("shared-widget__heading")}><div><h2>Kebutuhan</h2><span>{budgets.length} kebutuhan aktif</span></div><Link to="/anggaran">Lihat semua</Link></div><ul className={dashboardClass("shared-progress-list")}>{budgets.length ? budgets.slice(0, 3).map((item) => <li key={item.budget_id}><div><strong>{item.name || item.display_name || "Kebutuhan"}</strong><span><SensitiveMoney visible={balanceVisible} value={item.used_amount || 0} /> / <SensitiveMoney visible={balanceVisible} value={item.amount || 0} /></span></div><ProgressBar value={item.used_amount || 0} max={item.amount || 0} label={`Pemakaian ${item.name || "kebutuhan"}`} /></li>) : <li className={dashboardClass("shared-widget-empty")}><span>Belum ada kebutuhan aktif.</span><Link to="/perencanaan/kantong">Atur kebutuhan</Link></li>}</ul></article>;
const RecurringWidget = ({ items, balanceVisible }) => <article className={dashboardClass("shared-panel shared-widget")}><div className={dashboardClass("shared-widget__heading")}><div><h2>Jadwal terdekat</h2><span>{items.length} perlu dipantau</span></div><Link to="/perencanaan/jadwal">Lihat semua</Link></div><ul className={dashboardClass("shared-due-list")}>{items.length ? items.map((item) => <li key={item.occurrence_id || item.recurring_rule_id}><span className={dashboardClass("shared-due-icon")}><FiCalendar aria-hidden="true" /></span><span><strong>{item.name}</strong><small>{compactDate(item.due_date)} · <SensitiveMoney visible={balanceVisible} value={item.expected_amount || item.amount || 0} /></small></span><em>{dueLabel(item.due_date)}</em></li>) : <li className={dashboardClass("shared-widget-empty")}><span>Belum ada jadwal rutin mendatang.</span><Link to="/perencanaan/jadwal">Buat jadwal rutin</Link></li>}</ul></article>;
const GoalsWidget = ({ goals, balanceVisible }) => <article className={dashboardClass("shared-panel shared-widget")}><div className={dashboardClass("shared-widget__heading")}><div><h2>Target tabungan</h2><span>{goals.length} target aktif</span></div><Link to="/target">Lihat semua</Link></div><ul className={dashboardClass("shared-progress-list shared-goal-list")}>{goals.length ? goals.map((item) => <li key={item.goal_id}><div><strong><FiTarget aria-hidden="true" />{item.name}</strong><span><SensitiveMoney visible={balanceVisible} value={item.current_amount || 0} /> / <SensitiveMoney visible={balanceVisible} value={item.target_amount || 0} /></span></div><ProgressBar value={item.current_amount || 0} max={item.target_amount || 0} label={`Kemajuan ${item.name}`} /></li>) : <li className={dashboardClass("shared-widget-empty")}><span>Belum ada target tabungan aktif.</span><Link to="/target">Buat target</Link></li>}</ul></article>;
const InsightWidget = ({ model, overview, balanceVisible }) => {
  const [alertsOpen, setAlertsOpen] = useState(false);
  const freeFundsGuidance = dashboardAlertGuidance({ type: "unallocated_funds", id: `unallocated-funds:${overview.periodKey}`, targetPath: "/perencanaan/kantong" });
  return <>
    <article className={dashboardClass("shared-panel shared-widget shared-insight-widget")}>
      <div className={dashboardClass("shared-widget__heading")}><h2>Ringkasan</h2><FiAlertCircle aria-hidden="true" /></div>
      <dl>
        <div><dt><FiCreditCard aria-hidden="true" />Rekening aktif</dt><dd>{model.accountBalances.length}</dd></div>
        <div><dt><FiArrowDownLeft aria-hidden="true" />Transaksi rekening</dt><dd>{model.selectedAccountTransactions.length}</dd></div>
        <div><dt><FiFlag aria-hidden="true" />Dana belum dialokasikan</dt><dd><Link to={freeFundsGuidance.to} state={freeFundsGuidance.state} aria-label="Atur dana belum dialokasikan"><SensitiveMoney visible={balanceVisible} value={overview.unallocatedFunds || 0} /></Link></dd></div>
        <div><dt><FiArrowUpRight aria-hidden="true" />Peringatan aktif</dt><dd>{model.alerts.length}</dd></div>
      </dl>
      {model.alerts.length ? <button type="button" className={dashboardClass("shared-widget__link-button")} onClick={() => setAlertsOpen(true)}>Lihat peringatan</button> : <Link to="/laporan">Lihat insight detail</Link>}
    </article>
    <Modal open={alertsOpen} onClose={() => setAlertsOpen(false)} title="Perlu perhatian" description="Periksa detailnya lalu lanjutkan ke halaman tujuan. Membuka peringatan tidak mengubah data keuangan." size="md">
      <FinancialAlertList alerts={model.alerts} variant="dashboard" />
    </Modal>
  </>;
};
const InvestmentWidget = ({ summary, balanceVisible }) => summary ? <article className={dashboardClass("shared-panel shared-widget")}><div className={dashboardClass("shared-widget__heading")}><div><h2>Investasi</h2><span>{summary.holding_count || 0} saham tercatat</span></div><Link to="/investasi">Buka catatan</Link></div><dl><div><dt>Total aset investasi</dt><dd><SensitiveMoney visible={balanceVisible} value={summary.portfolio_value || 0} /></dd></div><div><dt>Cash RDN</dt><dd><SensitiveMoney visible={balanceVisible} value={summary.rdn_cash || 0} /></dd></div><div><dt>P/L belum direalisasi</dt><dd><SensitiveMoney visible={balanceVisible} value={summary.unrealized_pl || 0} tone={Number(summary.unrealized_pl || 0) < 0 ? "negative" : "positive"} /></dd></div></dl><Link to="/investasi">Buka catatan investasi</Link></article> : null;
const DashboardWidgets = ({ model, overview, investmentSummary, balanceVisible }) => <section className={dashboardClass("shared-dashboard-widgets")} aria-label="Perencanaan dan ringkasan"><BudgetWidget budgets={model.budgets} balanceVisible={balanceVisible} /><RecurringWidget items={model.recurringItems} balanceVisible={balanceVisible} /><GoalsWidget goals={model.goals} balanceVisible={balanceVisible} /><InvestmentWidget summary={investmentSummary} balanceVisible={balanceVisible} /><InsightWidget model={model} overview={overview} balanceVisible={balanceVisible} /></section>;

const DesktopFinanceDashboard = ({ overview, bootstrap, viewModel, investmentSummary, displayName, selectedAccountId, onSelectAccount, categoryFilter, setCategoryFilter, typeFilter, setTypeFilter, searchTerm, setSearchTerm, selectedTransactionId, setSelectedTransactionId, balanceVisible, onToggleBalance, onRefresh, onOpenTransaction, setupContent }) => {
  const model = buildDesktopModel({ overview, viewModel, selectedAccountId, categoryFilter, typeFilter, searchTerm, selectedTransactionId });
  return <div className={dashboardClass("dashboard-desktop shared-dashboard")}><DashboardHeader overview={overview} displayName={displayName} balanceVisible={balanceVisible} onToggleBalance={onToggleBalance} onRefresh={onRefresh} onOpenTransaction={onOpenTransaction} />{setupContent}<div className={dashboardClass("shared-dashboard__layout")}><div className={dashboardClass("shared-dashboard__main")}><AccountSelector accountBalances={model.accountBalances} selectedAccount={model.selectedAccount} onSelectAccount={onSelectAccount} balanceVisible={balanceVisible} /><AccountTransactions model={model} bootstrap={bootstrap} categoryFilter={categoryFilter} setCategoryFilter={setCategoryFilter} typeFilter={typeFilter} setTypeFilter={setTypeFilter} searchTerm={searchTerm} setSearchTerm={setSearchTerm} setSelectedTransactionId={setSelectedTransactionId} balanceVisible={balanceVisible} /></div><StatisticsPanel overview={overview} model={model} balanceVisible={balanceVisible} /></div><DashboardWidgets model={model} overview={overview} investmentSummary={investmentSummary} balanceVisible={balanceVisible} /></div>;
};

export default DesktopFinanceDashboard;
