export const TRANSACTION_TYPES = Object.freeze({
  INCOME: "income",
  EXPENSE: "expense",
  TRANSFER: "transfer",
  REFUND: "refund",
  ADJUSTMENT: "adjustment",
});

export const ACTIVE_STATUS = "active";
export const CANCELLED_STATUS = "cancelled";

export const ROLE_PERMISSIONS = Object.freeze({
  owner: new Set([
    "system.initialize",
    "system.health",
    "bootstrap.get",
    "users.list",
    "users.upsert",
    "users.deactivate",
    "audit.list",
    "dashboard.overview",
    "accounts.list",
    "accounts.create",
    "accounts.update",
    "accounts.archive",
    "categories.list",
    "categories.create",
    "categories.update",
    "categories.archive",
    "transactions.list",
    "transactions.create",
    "transactions.update",
    "transactions.cancel",
    "envelopes.list",
    "envelopes.createRule",
    "envelopes.createPeriod",
    "envelopes.move",
    "envelopes.close",
    "recurring.list",
    "recurring.createRule",
    "recurring.updateRule",
    "recurring.payOccurrence",
    "budgets.list",
    "budgets.upsert",
    "goals.list",
    "goals.create",
    "goals.move",
    "reports.monthly",
    "reconciliations.create",
    "periods.close",
    "periods.reopen",
    "calendar.sync",
    "notifications.register",
    "notifications.unregister",
    "backup.create",
    "export.create",
    "import.preview",
    "import.apply",
    "restore.preview",
    "restore.apply",
    "integrity.run",
  ]),
  member: new Set([
    "system.health",
    "bootstrap.get",
    "dashboard.overview",
    "accounts.list",
    "categories.list",
    "transactions.list",
    "transactions.create",
    "transactions.update",
    "transactions.cancel",
    "envelopes.list",
    "envelopes.move",
    "recurring.list",
    "recurring.payOccurrence",
    "budgets.list",
    "goals.list",
    "goals.move",
    "reports.monthly",
    "reconciliations.create",
    "notifications.register",
    "notifications.unregister",
  ]),
});

export const DEFAULT_TIMEZONE = "Asia/Jakarta";
export const DEFAULT_CURRENCY = "IDR";
