const definePolicy = (mode, { maintenanceAllowed = false, idempotencyRequired = false, retryUnknownSafe = false } = {}) => Object.freeze({
  mode,
  maintenanceAllowed,
  idempotencyRequired,
  retryUnknownSafe,
});

const read = (options) => definePolicy("read", options);
const write = (options = {}) => definePolicy("write", { idempotencyRequired: true, ...options });
const external = (options = {}) => definePolicy("external", { idempotencyRequired: true, ...options });

export const ACTION_POLICIES = Object.freeze({
  "system.health": read({ maintenanceAllowed: true }),
  "app.initialState": read(),
  "bootstrap.get": read(),
  "users.list": read(),
  "users.upsert": write(),
  "users.deactivate": write(),
  "users.reactivate": write(),
  "audit.list": read({ maintenanceAllowed: true }),
  "archive.list": read(),
  "dashboard.overview": read(),
  "accounts.list": read(),
  "accounts.create": write(),
  "accounts.update": write(),
  "accounts.previewLifecycle": read(),
  "accounts.archive": write(),
  "accounts.restore": write(),
  "accounts.deleteUnused": write(),
  "categories.list": read(),
  "categories.create": write(),
  "categories.update": write(),
  "categories.previewArchive": read(),
  "categories.archive": write(),
  "categories.restore": write(),
  "categories.deleteUnused": write(),
  "transactions.list": read(),
  "transactions.create": write(),
  "transactions.update": write(),
  "transactions.cancel": write(),
  "transactions.restore": write(),
  "envelopes.list": read(),
  "envelopes.create": write(),
  "envelopes.move": write(),
  "envelopes.close": write(),
  "envelopes.previewRuleLifecycle": read(),
  "envelopes.archiveRule": write(),
  "envelopes.deleteUnusedRule": write(),
  "envelopes.restoreRule": write(),
  "envelopes.reverseMovement": write(),
  "recurring.list": read(),
  "recurring.createRule": write(),
  "recurring.updateRule": write(),
  "recurring.previewRuleLifecycle": read(),
  "recurring.archiveRule": write(),
  "recurring.deleteUnusedRule": write(),
  "recurring.cancelOccurrence": write(),
  "recurring.restoreOccurrence": write(),
  "recurring.payOccurrence": write(),
  "recurring.reversePayment": write(),
  "recurring.restoreRule": write(),
  "budgets.list": read(),
  "budgets.upsert": write(),
  "budgets.previewLifecycle": read(),
  "budgets.archive": write(),
  "budgets.deleteUnused": write(),
  "budgets.restore": write(),
  "goals.list": read(),
  "goals.create": write(),
  "goals.update": write(),
  "goals.previewLifecycle": read(),
  "goals.archive": write(),
  "goals.deleteUnused": write(),
  "goals.move": write(),
  "goals.reverseMovement": write(),
  "goals.restore": write(),
  "reports.monthly": read(),
  "reconciliations.list": read(),
  "reconciliations.create": write(),
  "periods.list": read(),
  "periods.previewClose": read(),
  "periods.close": write(),
  "periods.reopen": write(),
  "notifications.status": read(),
  "notifications.preferences": read(),
  "notifications.updatePreference": write(),
  "notifications.register": write(),
  "notifications.unregister": write(),
  "notifications.test": external(),
  "calendar.sync": write(),
  "mirror.sync": write(),
  "mirror.rebuild": write(),
  "integrations.status": read({ maintenanceAllowed: true }),
  "backup.create": external({ maintenanceAllowed: true, retryUnknownSafe: true }),
  "import.preview": write(),
  "import.apply": external({ retryUnknownSafe: true }),
  "restore.preview": external({ maintenanceAllowed: true, retryUnknownSafe: true }),
  "restore.apply": external({ maintenanceAllowed: true, retryUnknownSafe: true }),
  "integrity.run": write({ maintenanceAllowed: true }),
});

export const getActionPolicy = (action) => ACTION_POLICIES[action] || null;
export const isReadAction = (action) => getActionPolicy(action)?.mode === "read";
export const isExternalAction = (action) => getActionPolicy(action)?.mode === "external";
export const isMaintenanceAllowedAction = (action) => Boolean(getActionPolicy(action)?.maintenanceAllowed);
export const requiresIdempotencyKey = (action) => Boolean(getActionPolicy(action)?.idempotencyRequired);
export const actionNames = () => Object.keys(ACTION_POLICIES);
